## Sem3

## Задание 1.
1. Скачать данные по ссылке
https://www.kaggle.com/datasets/ionaskel/laptop-prices
2. Считать данные с помощью pandas
3. Вывести на экран первые 5 строк

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./laptop_price.csv',encoding='windows-1251')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

### 1.1 Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU

In [3]:
df['Cpu'].value_counts()

Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core M M3-6Y30 0.9GHz        1
AMD A9-Series 9420 2.9GHz          1
Intel Core i3 6006U 2.2GHz         1
AMD A6-Series 7310 2GHz            1
Intel Xeon E3-1535M v6 3.1GHz      1
Name: Cpu, Length: 118, dtype: int64

In [4]:
df['Cpu_company'] = df['Cpu'].apply(lambda row: row.split()[0])
df.sample(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_company
66,68,HP,250 G6,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,500GB HDD,AMD Radeon 520,Windows 10,1.86kg,438.69,Intel
617,624,HP,EliteBook 850,Ultrabook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.84kg,1389.00,Intel
343,349,Lenovo,Yoga 920-13IKB,2 in 1 Convertible,13.9,IPS Panel 4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Intel UHD Graphics 620,Windows 10,1.4kg,2099.00,Intel
1020,1034,Dell,Inspiron 5568,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i3 6100U 2.3GHz,4GB,1TB HDD,Intel HD Graphics 520,Windows 10,2.08kg,795.99,Intel
956,970,Dell,XPS 13,2 in 1 Convertible,13.3,Full HD / Touchscreen 1920x1080,Intel Core i5 7Y54 1.2GHz,8GB,256GB SSD,Intel HD Graphics 615,Windows 10,1.24kg,1899.00,Intel

### 1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [5]:
df.Memory.value_counts()

256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: Memory, dtype: int64

In [6]:
# 512GB SSD +  1.0TB Hybrid  
def get_gb(row: str) -> str:
    gb = 0
    row_list = row.split()
    for el in row_list:
        if 'GB' in el:
            gb += int(el[:-2])
        elif 'TB' in el:
            gb += float(el[:-2]) * 1024
    return int(gb)

df['Memory_Amount'] = df['Memory'].apply(get_gb)
df.sample(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount
412,419,HP,15-BS028nv (i3-6006U/4GB/1TB/Radeon,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,1TB HDD,AMD Radeon 520,Windows 10,2.1kg,469.00,Intel,1024
80,82,Dell,Latitude 5590,Ultrabook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.88kg,1096.16,Intel,256
534,541,Asus,ROG Strix,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.3kg,1649.00,Intel,1152
1110,1125,HP,EliteBook 1030,Notebook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core M 6Y54 1.1GHz,8GB,256GB SSD,Intel HD Graphics 515,Windows 10,1.16kg,1699.00,Intel,256
244,249,Lenovo,Yoga 910-13IKB,2 in 1 Convertible,13.9,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.38kg,1079.00,Intel,256

### 1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.)

In [7]:
# 64GB Flash Storage +  1TB HDD

def get_type(row: str) -> str:
    type_memory = ''
    row_list = row.split()
    for el in row_list:
        if 'GB' not in el and 'TB' not in el and el not in type_memory:
            type_memory += el + ''
    return type_memory.rstrip().rstrip(' +')

df['Memory_Type'] = df['Memory'].apply(get_type)
df.sample(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type
175,179,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 7100U 2.4GHz,8GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,459.0,Intel,1024,HDD
433,440,Lenovo,Thinkpad T570,Workstation,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7600U 2.8GHz,16GB,512GB SSD,Nvidia GeForce 940MX,Windows 10,2.3kg,2445.0,Intel,512,SSD
1036,1050,HP,ProBook 450,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,2.04kg,742.0,Intel,500,HDD
1296,1314,HP,Stream 11-Y000na,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.17kg,209.0,Intel,32,FlashStorage
189,193,Dell,Inspiron 5770,Notebook,17.3,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,128GB SSD + 1TB HDD,AMD Radeon 530,Windows 10,2.8kg,1085.0,Intel,1152,SSD+HDD

In [8]:
df.Memory_Type.value_counts()

SSD                 641
HDD                 375
SSD+HDD             200
FlashStorage         74
Hybrid               10
SSD+Hybrid            2
FlashStorage+HDD      1
Name: Memory_Type, dtype: int64

### Второй способ

In [9]:
# def get_type(row: str) -> str:
#     type_memory = ''
#     row_list = row.split()
#     for el in row_list:
#         if el.isalpha() and el not in type_memory:
#             type_memory += el + ' '
#     return type_memory.rstrip()

# df['Memory_Type2'] = df['Memory'].apply(get_type)
# df['Memory_Type2'].value_counts()



### 1.4 Удалите признаки Memory и ScreenResolution

In [10]:
df.drop(columns = ['Memory','ScreenResolution'],inplace = True)
df.sample()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type
1198,1216,Acer,Aspire 3,Notebook,15.6,Intel Celeron Dual Core N3350 2GHz,4GB,Intel HD Graphics 500,Linux,2.1kg,272.0,Intel,1024,HDD

## Задание 2.

### 2.1 Создайте признак SSD, который изначально равен 0

In [11]:
df['SSD'] = 0
df.sample()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
607,614,Lenovo,IdeaPad 310-15IKB,Notebook,15.6,Intel Core i5 7200U 2.5GHz,6GB,Intel HD Graphics 620,Windows 10,2.4kg,564.0,Intel,1024,HDD,0

### 2.2 Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [12]:
df.loc[df['Memory_Type'] == 'SSD', 'SSD'] = 1
df.sample(10)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
314,319,Asus,VivoBook Flip,2 in 1 Convertible,11.6,Intel Celeron Dual Core N3350 1.1GHz,2GB,Intel HD Graphics 500,Windows 10,1.1kg,275.0,Intel,32,FlashStorage,0
1109,1124,Asus,Rog GL552VW-CN470T,Gaming,15.6,Intel Core i7 6700HQ 2.6GHz,16GB,Nvidia GeForce GTX 960M,Windows 10,2.59kg,1339.0,Intel,1152,SSD+HDD,0
633,641,Lenovo,Ideapad 320-15ISK,Notebook,15.6,Intel Core i3 6006U 2GHz,4GB,Nvidia GeForce 920MX,Windows 10,2.2kg,579.0,Intel,1024,HDD,0
288,293,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.5kg,1179.0,Intel,1280,SSD+HDD,0
798,807,Lenovo,Yoga 910-13IKB,2 in 1 Convertible,13.9,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,1.38kg,1349.0,Intel,256,SSD,1
1274,1292,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,Intel Celeron Dual Core N3050 1.6GHz,4GB,Intel HD Graphics,Windows 10,2.2kg,369.0,Intel,500,HDD,0
953,967,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Intel Core M M7-6Y75 1.2GHz,8GB,Intel HD Graphics 515,Chrome OS,1.2kg,1159.0,Intel,64,FlashStorage,0
504,511,Lenovo,Chromebook N23,Netbook,11.6,Intel Celeron Dual Core N3060 1.6GHz,4GB,Intel HD Graphics 400,Chrome OS,1.25kg,265.0,Intel,16,SSD,1
600,607,HP,EliteBook 850,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,1.84kg,1219.0,Intel,256,SSD,1
85,87,Dell,Inspiron 7577,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.65kg,1349.0,Intel,1152,SSD+HDD,0

In [13]:
df.loc[df['Memory_Type'].str.contains('SSD'), 'SSD'] = 1
df.sample(10)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
610,617,Lenovo,Thinkpad P51,Notebook,15.6,Intel Xeon E3-1535M v6 3.1GHz,32GB,Nvidia Quadro M2200M,Windows 10,2.5kg,4899.00,Intel,1024,SSD,1
572,579,HP,15-cd005nv (A9-9420/6GB/256GB/Radeon,Notebook,15.6,AMD A9-Series A9-9420 3GHz,6GB,AMD Radeon 530,Windows 10,1.95kg,649.00,AMD,256,SSD,1
1108,1123,HP,15-bw011nv (A6-9220/4GB/1TB/FHD/W10),Notebook,15.6,AMD A6-Series 9220 2.5GHz,4GB,AMD Radeon R4,Windows 10,2.1kg,398.00,AMD,1024,HDD,0
551,558,Dell,Latitude 5580,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,1.9kg,1116.99,Intel,256,SSD,1
620,627,HP,ProBook 650,Notebook,14.0,Intel Core i5 7300U 2.6GHz,8GB,Intel HD Graphics 620,Windows 10,2.31kg,1124.00,Intel,256,SSD,1
1041,1055,Vero,V142 (X5-Z8350/2GB/32GB/W10),Notebook,14.0,Intel Atom X5-Z8350 1.44GHz,2GB,Intel HD Graphics 400,Windows 10,1.45kg,210.80,Intel,32,FlashStorage,0
776,785,Lenovo,Thinkpad P50,Notebook,15.6,Intel Core i7 6820HQ 2.7GHz,16GB,Nvidia Quadro M2000M,Windows 7,2.5kg,2370.00,Intel,512,SSD,1
184,188,Xiaomi,Mi Notebook,Notebook,15.6,Intel Core i5 8250U 1.6GHz,8GB,Nvidia GeForce MX150,No OS,1.95kg,1199.00,Intel,256,SSD,1
22,23,HP,255 G6,Notebook,15.6,AMD E-Series E2-9000e 1.5GHz,4GB,AMD Radeon R2,No OS,1.86kg,258.00,AMD,500,HDD,0
1081,1096,Lenovo,IdeaPad Y900-17ISK,Gaming,17.3,Intel Core i7 6820HK 2.7GHz,32GB,Nvidia GeForce GTX 980M,Windows 10,4.6kg,3240.00,Intel,1536,SSD+Hybrid,1

### 2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [14]:
df.Weight.str.replace('kg', '').astype('float')

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: Weight, Length: 1303, dtype: float64

In [15]:
df.Weight = df.Weight.apply(lambda row: row[:-2]).astype('float')
df.sample(10)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
949,963,Acer,Chromebook 14,Notebook,14.0,Intel Celeron Dual Core N3060 1.6GHz,4GB,Intel HD Graphics 400,Chrome OS,1.68,349.0,Intel,32,FlashStorage,0
1239,1257,Lenovo,ThinkPad 13,Notebook,13.3,Intel Core i7 7500U 2.7GHz,16GB,Intel HD Graphics 620,Windows 10,1.40,1499.0,Intel,512,SSD,1
304,309,Asus,GL553VE-FY082T (i7-7700HQ/8GB/1TB,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1265.0,Intel,1152,SSD+HDD,1
968,982,Dell,Alienware 17,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,32GB,Nvidia GeForce GTX 1070,Windows 10,4.42,3149.0,Intel,1280,SSD+HDD,1
251,256,Asus,ROG G752VSK-GC493T,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 980M,Windows 10,4.30,1799.0,Intel,1280,SSD+HDD,1
757,766,HP,ZBook 15,Workstation,15.6,Intel Core i7 6700HQ 2.6GHz,8GB,Nvidia Quadro M1000M,Windows 7,2.59,1561.0,Intel,256,SSD,1
476,483,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2408.0,Intel,256,SSD,1
743,751,Lenovo,Flex 5,2 in 1 Convertible,14.0,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,1.70,999.0,Intel,256,SSD,1
794,803,Apple,"MacBook 12""",Ultrabook,12.0,Intel Core M 1.2GHz,8GB,Intel HD Graphics 5300,Mac OS X,0.92,1165.0,Intel,512,FlashStorage,0
1058,1072,Dell,Inspiron 7378,2 in 1 Convertible,13.3,Intel Core i7 7500U 2.7GHz,12GB,Intel HD Graphics 620,Windows 10,1.60,1299.0,Intel,256,SSD,1

## Задание 3.
Создайте датафрейм с клиентами:
clients = pd.DataFrame({
 'client_id': [45, 32, 67, 33, 43],
 'laptop_id': [506, 398, 710, 120, 1999]
})
laptop_id - это индексы датафрейма с ноутбуками

In [16]:
clients = pd.DataFrame({
 'client_id': [45, 32, 67, 33, 43],
 'laptop_id': [506, 398, 710, 120, 1999]
})
clients

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

### 3.1 Присоедините к таблице clients данные по ноутбукам через метод join

In [17]:
clients_id = clients.set_index('laptop_id')
clients_id

           client_id
laptop_id
506               45
398               32
710               67
120               33
1999              43

In [18]:
df.sample()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
440,447,Lenovo,IdeaPad 320-15AST,Notebook,17.3,AMD A6-Series 9220 2.5GHz,8GB,AMD Radeon R4,Windows 10,2.8,519.0,AMD,1024,HDD,0

In [19]:
df_id = df.set_index('laptop_ID')
df_id.sample()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
laptop_ID,,,,,,,,,,,,,,
478,HP,ZBook 15u,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,AMD FirePro W4190M,Windows 10,1.9,1154.0,Intel,500,HDD,0

In [20]:
clients_id.join(df_id)

,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
laptop_id,,,,,,,,,,,,,,,
506,45,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256.0,SSD,1.0
398,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,67,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024.0,HDD,0.0
120,33,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,1280.0,SSD+HDD,1.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
clients_id.merge(df_id, left_index=True, right_index=True, how='left')

,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
laptop_id,,,,,,,,,,,,,,,
506,45,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256.0,SSD,1.0
398,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,67,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024.0,HDD,0.0
120,33,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,1280.0,SSD+HDD,1.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 3.2 Присоедините к таблице clients данные по ноутбукам через метод merge 
Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

In [23]:
clients.merge(df, left_on = 'laptop_id', right_on = 'laptop_ID', how='left')

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
0,45,506,506.0,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256.0,SSD,1.0
1,32,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67,710,710.0,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024.0,HDD,0.0
3,33,120,120.0,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,1280.0,SSD+HDD,1.0
4,43,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Задание 4.
Составьте несколько сводных таблиц

### 4.1 Найдите среднюю стоимость ноутбуков в зависимости от компании производителя
Отсортируйте от меньшей стоимости к большей

In [26]:
df.groupby('Company').agg({'Price_euros': 'mean'}).sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

In [28]:
df.groupby('Company').Price_euros.mean().sort_values()

Company
Vero          217.425000
Mediacom      295.000000
Chuwi         314.296667
Acer          626.775825
Fujitsu       729.000000
HP           1067.774854
Lenovo       1086.384444
Asus         1104.169367
Xiaomi       1133.462500
Dell         1186.068990
Toshiba      1267.812500
Samsung      1413.444444
Huawei       1424.000000
Apple        1564.198571
Microsoft    1612.308333
Google       1677.666667
MSI          1728.908148
LG           2099.000000
Razer        3346.142857
Name: Price_euros, dtype: float64

### 4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [30]:
df.groupby('Company').agg({'Price_euros': ['min', 'mean', 'max']})

          Price_euros
                  min         mean      max
Company
Acer           174.00   626.775825  2599.00
Apple          898.94  1564.198571  2858.00
Asus           191.90  1104.169367  3975.00
Chuwi          244.99   314.296667   449.00
Dell           274.90  1186.068990  3659.40
Fujitsu        649.00   729.000000   799.00
Google        1275.00  1677.666667  2199.00
HP             209.00  1067.774854  4389.00
Huawei        1349.00  1424.000000  1499.00
LG            1899.00  2099.000000  2299.00
Lenovo         229.00  1086.384444  4899.00
MSI            839.00  1728.908148  2799.00
Mediacom       239.00   295.000000   389.00
Microsoft      989.00  1612.308333  2589.00
Razer         1029.00  3346.142857  6099.00
Samsung        269.00  1413.444444  1849.00
Toshiba        447.00  1267.812500  2799.00
Vero           196.00   217.425000   260.00
Xiaomi         935.00  1133.462500  1399.95

### 4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [33]:
df.sample()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
195,199,HP,ProBook 470,Notebook,17.3,Intel Core i5 8250U 1.6GHz,8GB,Nvidia GeForce 930MX,Windows 10,2.5,914.0,Intel,1024,HDD,0

In [39]:
df.pivot_table(index = 'Cpu_company',columns = 'Ram', aggfunc='count', values='Company', fill_value=0)

Ram          12GB  16GB  24GB  2GB  32GB  4GB  64GB  6GB  8GB
Cpu_company
AMD             2     3     0    1     0   31     0   13   12
Intel          23   197     3   21    17  343     1   28  607
Samsung         0     0     0    0     0    1     0    0    0

### 4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [40]:
df.head(1)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1

In [44]:
df.groupby(['OpSys', 'Memory_Amount']).agg({'Price_euros': 'mean'}).unstack('Memory_Amount').fillna(0).round(2)

              Price_euros                                                   \
Memory_Amount        8       16      32      64       128     180     240
OpSys
Android               0.0    0.00    0.00  434.00     0.00     0.0     0.0
Chrome OS             0.0  305.38  412.45  774.33  1275.00     0.0     0.0
Linux                 0.0    0.00    0.00    0.00   490.50     0.0     0.0
Mac OS X              0.0    0.00    0.00    0.00  1099.00     0.0     0.0
No OS                 0.0    0.00    0.00    0.00   362.02     0.0     0.0
Windows 10         2249.0    0.00  270.00  333.80   673.39  1073.5  3100.0
Windows 10 S          0.0    0.00    0.00  309.00  1039.00     0.0     0.0
Windows 7             0.0    0.00    0.00    0.00  1320.32  1199.0     0.0
macOS                 0.0    0.00    0.00    0.00  1119.32     0.0     0.0

                                        ...                            \
Memory_Amount     256     500     508   ...     768      1024    1088
OpSys                                   ...
Android           0.00    0.00     0.0  ...     0.00     0.00     0.0
Chrome OS      1559.00    0.00     0.0  ...     0.00     0.00     0.0
Linux           795.81  389.06     0.0  ...     0.00   581.40     0.0
Mac OS X       1311.99    0.00     0.0  ...     0.00     0.00     0.0
No OS           754.83  404.68     0.0  ...     0.00   540.54     0.0
Windows 10     1214.52  664.72     0.0  ...  1607.96   880.70  1993.0
Windows 10 S   1668.95    0.00     0.0  ...     0.00     0.00     0.0
Windows 7      1846.47  924.05  1002.0  ...     0.00  1539.67     0.0
macOS          1600.37    0.00     0.0  ...     0.00     0.00     0.0


Memory_Amount     1152     1280     1536    2048    2176     2304    2560
OpSys
Android           0.00     0.00     0.00     0.0    0.00     0.00     0.0
Chrome OS         0.00     0.00     0.00     0.0    0.00     0.00     0.0
Linux           994.00     0.00     0.00     0.0    0.00  1049.00     0.0
Mac OS X          0.00     0.00     0.00     0.0    0.00     0.00     0.0
No OS           895.67  1149.00     0.00   594.0    0.00     0.00     0.0
Windows 10     1285.46  1878.08  2549.75  1058.2  977.95  1590.02  1849.0
Windows 10 S      0.00     0.00     0.00     0.0    0.00     0.00     0.0
Windows 7         0.00     0.00     0.00     0.0    0.00     0.00     0.0
macOS             0.00     0.00     0.00     0.0    0.00     0.00     0.0

[9 rows x 22 columns]

## Задание 5*.
Ответьте на несколько вопросов

### 5.1 Ноутбуков каких компаний и с каким процессором больше?

In [45]:
pd.crosstab(index = df['Company'],
           columns = df['Cpu_company'])

Cpu_company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

### 5.2 С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [46]:
pd.crosstab(index = df['Memory_Type'],
           columns = df['Memory_Amount'])

Memory_Amount,8,16,32,64,128,180,240,256,500,508,...,768,1024,1088,1152,1280,1536,2048,2176,2304,2560
Memory_Type,,,,,,,,,,,,,,,,,,,,,
FlashStorage,0,7,38,15,4,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
FlashStorage+HDD,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
HDD,0,0,1,0,1,0,0,0,132,0,...,0,224,0,0,0,0,17,0,0,0
Hybrid,0,0,0,0,0,0,0,0,0,1,...,0,9,0,0,0,0,0,0,0,0
SSD,1,3,6,1,76,5,1,412,0,0,...,1,15,0,0,0,0,0,0,0,0
SSD+HDD,0,0,0,0,0,0,0,0,0,0,...,0,0,0,94,73,14,2,2,10,3
SSD+Hybrid,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0

In [47]:
pd.set_option('display.max_columns', None)
pd.crosstab(index = df['Memory_Type'],
           columns = df['Memory_Amount'])

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,756,768,1024,1088,1152,1280,1536,2048,2176,2304,2560
Memory_Type,,,,,,,,,,,,,,,,,,,,,,
FlashStorage,0,7,38,15,4,0,0,8,0,0,2,0,0,0,0,0,0,0,0,0,0,0
FlashStorage+HDD,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
HDD,0,0,1,0,1,0,0,0,132,0,0,0,0,224,0,0,0,0,17,0,0,0
Hybrid,0,0,0,0,0,0,0,0,0,1,0,0,0,9,0,0,0,0,0,0,0,0
SSD,1,3,6,1,76,5,1,412,0,0,120,0,1,15,0,0,0,0,0,0,0,0
SSD+HDD,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,94,73,14,2,2,10,3
SSD+Hybrid,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0